### PR TITLE
feature(darwin): Example of specialArgs usage.

### PR DESCRIPTION
**Pull request by licebmi**
I think the templates should be a way to discover features of the system, it took a long time until I learned about this feature.

### CODE REVIEW

**Comment by isabelroses** [comment]
This probably should have been fixed by https://github.com/auxolotl/templates/pull/3, but i agree it would be a good idea to document how specialArgs are used.

**Comment by getchoo** [comment]
why not document what we can do with `inputs`? i don't see a reason to use `username` specifically for this

**Comment by licebmi** [comment]
@getchoo With the inputs we have, the only sensible example I can think is to import home-manager outside of the flake; would this make sense?
The main objection I have is that `inputs` being an named set might appear more magical than just a straight forward "define a var -> use said var"

@isabelroses I agree, this seems like a regression taking that PR in account. How would rewriting this using the module system would look like?

Reference the specific user? I would argue that is against DRY.
``` nix
    trusted-users = [ config.users.users.<username>.name ];
```

Maybe using a function to get the defined users. It could work in darwin since most use macos as a single user system?
``` nix
        trusted-users = lib.attrNames config.users.users;
```

**Comment by licebmi** [comment]
After thinking this a little while, I wonder about the purpose of this PR.

I think discovery of features is still one of nix weak points, yet maybe the template not be the right place to tackle the issue.

What is the purpose of these templates? Being an introduction of nix/aux for newbies? Or being a way to quickstart seasoned nix users into our project?

I mean, in my use case, the flake structure is small and every time I use a template is because I just want to inspect how a project works, not really because I would actually use the template for a project of my own; but maybe I'm holding it wrong.

**Comment by isabelroses** [comment]
> Reference the specific user? I would argue that is against DRY.
> 
> ```nix
>     trusted-users = [ config.users.users.<username>.name ];
> ```
> 
> Maybe using a function to get the defined users. It could work in darwin since most use macos as a single user system?
> 
> ```nix
>         trusted-users = lib.attrNames config.users.users;
> ```

I think that DRY is not the biggest concern with this repo, but I do agree the second solution is a better one.

> The main objection I have is that inputs being an named set might appear more magical than just a straight forward "define a var -> use said var"

This is probably better saved for our oncoming documentation. I feel just inputs are good enough place to explain you can give a var as a specialArg.

**Comment by isabelroses** [comment]
> After thinking this a little while, I wonder about the purpose of this PR.
> 
> I think discovery of features is still one of nix weak points, yet maybe the template not be the right place to tackle the issue.

Yeah, this would be better for tracking in proper documentation. Since a template is just here to help users start getting their aux setup together. If you want to help with some of the docs see here -> https://forum.aux.computer/c/special-interest-groups/sig-documentation/21

> What is the purpose of these templates? Being an introduction of nix/aux for newbies? Or being a way to quickstart seasoned nix users into our project?

Ideally a quick starting place for newbies. But with gradual changes, between nix and aux hopefully it can help bridge the gap between a seasoned nix user and a seasoned aux user.

> I mean, in my use case, the flake structure is small and every time I use a template is because I just want to inspect how a project works, not really because I would actually use the template for a project of my own; but maybe I'm holding it wrong.

Thats fair for your use case, but I would argue thats not the intended use case. And we want to lean into our goal of keeping this as the entry point.

**Comment by licebmi** [comment]
@isabelroses 
Makes sense.

Closing this PR then.

**Pull request closed without merging**
